name: reddit
description: A community social media app - Reddit.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  flutter_riverpod: ^2.3.6
  fpdart: ^1.0.0
  routemaster: ^1.0.1
  dotted_border: ^2.0.0+3
  file_picker: ^5.3.3
  shared_preferences: ^2.2.0
  uuid: ^3.0.7
  any_link_preview: ^3.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:  
    - assets/images/
    - assets/images/awards/

  fonts:
    - family: myFont
      fonts:
        - asset: assets/fonts/myFont.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
